pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:ludayab/fixers.git
          - cd fixers.git
          - git push --mirror git@github.com:001elijah/my-team-repo
          