pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:001elijah/my-team-repo
          - cd my-team-repo.git
          - git push --mirror git@github.com:001elijah/my-team-repo
          